"""
SEPLE Email Digest Notifier
Sends tender digest emails using SMTP.
"""
import os
import logging
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

logger = logging.getLogger(__name__)


class EmailDigestNotifier:
    """Sends tender digest emails via SMTP."""

    def __init__(self):
        self.smtp_host = os.getenv("SMTP_HOST", "smtp.gmail.com")
        self.smtp_port = int(os.getenv("SMTP_PORT", "587"))
        self.smtp_user = os.getenv("SMTP_USER", "")
        self.smtp_password = os.getenv("SMTP_PASSWORD", "")
        self.from_email = os.getenv("EMAIL_FROM", self.smtp_user)
        self.to_emails = os.getenv("EMAIL_TO", "").split(",")

    def send_digest(self, tenders: list[dict], subject: str = None) -> bool:
        """
        Send a daily tender digest email.

        Args:
            tenders: List of tender dicts to include in the digest
            subject: Optional custom subject line

        Returns:
            True if email sent successfully
        """
        if not self.smtp_user or not self.to_emails[0]:
            logger.warning("Email not configured — skipping digest")
            return False

        if not subject:
            subject = f"SEPLE Tender Digest — {len(tenders)} New Tenders — {datetime.utcnow().strftime('%Y-%m-%d')}"

        html_body = self._build_html(tenders)

        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = self.from_email
        msg["To"] = ", ".join(self.to_emails)
        msg.attach(MIMEText(html_body, "html"))

        try:
            with smtplib.SMTP(self.smtp_host, self.smtp_port) as server:
                server.starttls()
                server.login(self.smtp_user, self.smtp_password)
                server.send_message(msg)

            logger.info(f"Digest email sent to {len(self.to_emails)} recipients")
            return True

        except Exception as e:
            logger.error(f"Email send failed: {e}")
            return False

    def _build_html(self, tenders: list[dict]) -> str:
        """Build HTML email body from tender list."""
        rows = ""
        for t in tenders[:20]:
            title = t.get("title", "Unknown")
            source = t.get("source", "—")
            value = t.get("value", {})
            val = value.get("formatted", "—") if isinstance(value, dict) else "—"
            deadline = t.get("deadline", "—")
            url = t.get("url", "#")

            rows += f"""
            <tr>
                <td style="padding:8px; border-bottom:1px solid #eee;">
                    <a href="{url}" style="color:#1a73e8; text-decoration:none;">{title}</a>
                </td>
                <td style="padding:8px; border-bottom:1px solid #eee;">{source}</td>
                <td style="padding:8px; border-bottom:1px solid #eee;">{val}</td>
                <td style="padding:8px; border-bottom:1px solid #eee;">{deadline}</td>
            </tr>
            """

        return f"""
        <html>
        <body style="font-family: Arial, sans-serif; color: #333;">
            <h2 style="color: #1a73e8;">📋 SEPLE Tender Digest</h2>
            <p>{len(tenders)} new tenders found on {datetime.utcnow().strftime('%B %d, %Y')}</p>
            <table style="width:100%; border-collapse:collapse;">
                <tr style="background:#f5f5f5;">
                    <th style="padding:8px; text-align:left;">Title</th>
                    <th style="padding:8px; text-align:left;">Source</th>
                    <th style="padding:8px; text-align:left;">Value</th>
                    <th style="padding:8px; text-align:left;">Deadline</th>
                </tr>
                {rows}
            </table>
            <p style="margin-top:20px; color:#888; font-size:12px;">
                Generated by SEPLE Tender Intelligence Platform
            </p>
        </body>
        </html>
        """
